### ISSUE TITLE
crypto hardening

### ISSUE THREAD

**Issue by neo-luddite** [systemli/ansible-sshd#9]
following bettercrypto.org

in ansible-sshd/templates/sshd_config.j2

disable dsa & ecdsa keys:

> #HostKey /etc/ssh/ssh_host_dsa_key
> #HostKey /etc/ssh/ssh_host_ecdsa_key

define more secure algos et al.

> Ciphers chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes128-gcm@openssh.\
\com,aes256-ctr,aes128-ctr
> MACs hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,umac-128-\
\etm@openssh.com,hmac-sha2-512,hmac-sha2-256,hmac-ripemd160
> KexAlgorithms curve25519-sha256@libssh.org,diffie-hellman-group-exchange-sha256,\
\diffie-hellman-group14-sha1,diffie-hellman-group-exchange-sha1

**Comment by t2d** [comment]
while I agree, that using other curves makes sense, denying ecdsa seems harsh to me.
same with the algos. isn't that something you mostly want in your client?
however, why don't you make a pull request, make ciphers a var and provide it as a default?

**Comment by xshadow** [comment]
Thanks @neo-luddite for the guidance. 

Added the possibility of setting hostkeys via variable and disabled: 

> #HostKey /etc/ssh/ssh_host_dsa_key
> #HostKey /etc/ssh/ssh_host_ecdsa_key

per default via e6dee2d5829314868cd4cdb2cb59608562c7e843
